"""empty message

Revision ID: 2002df49b364
Revises: 
Create Date: 2021-09-18 01:14:42.619423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2002df49b364'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=10), nullable=False),
    sa.Column('vehicle_class', sa.String(length=30), nullable=False),
    sa.Column('crews', sa.String(length=30), nullable=False),
    sa.Column('manufacturer', sa.String(length=30), nullable=False),
    sa.Column('cost_in_credits', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('user')
    # ### end Alembic commands ###
