"""empty message

Revision ID: 75117d94a0f0
Revises: f43aa64c93d7
Create Date: 2021-09-19 16:30:52.810489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75117d94a0f0'
down_revision = 'f43aa64c93d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('hair_color', sa.String(length=30), nullable=False),
    sa.Column('eye_color', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
